name: Build Vue
on:
  push:
    branches: [master]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'FluxCapacitor2'
        reponame: 'WebQuiz'
        token: ${{ secrets.GITHUB_TOKEN }}
